// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnT5B3rzu-WUD2sA6Ar25DnnNd2VZVB6o',
    appId: '1:170939507034:web:fb6cadace4899842c7d363',
    messagingSenderId: '170939507034',
    projectId: 'resik-sampah',
    authDomain: 'resik-sampah.firebaseapp.com',
    storageBucket: 'resik-sampah.firebasestorage.app',
    measurementId: 'G-69L20B5944',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnxIq1RkZ9vRkRBssHFFvtOatOjX6xH0',
    appId: '1:170939507034:android:e11d7b419d6054e4c7d363',
    messagingSenderId: '170939507034',
    projectId: 'resik-sampah',
    storageBucket: 'resik-sampah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQKIO17M1r0Fg9xDEb8OU5tgfNoIlPtsU',
    appId: '1:170939507034:ios:7718e9a1d23bc138c7d363',
    messagingSenderId: '170939507034',
    projectId: 'resik-sampah',
    storageBucket: 'resik-sampah.firebasestorage.app',
    iosBundleId: 'com.example.resik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQKIO17M1r0Fg9xDEb8OU5tgfNoIlPtsU',
    appId: '1:170939507034:ios:7718e9a1d23bc138c7d363',
    messagingSenderId: '170939507034',
    projectId: 'resik-sampah',
    storageBucket: 'resik-sampah.firebasestorage.app',
    iosBundleId: 'com.example.resik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnT5B3rzu-WUD2sA6Ar25DnnNd2VZVB6o',
    appId: '1:170939507034:web:c84bae678e2d4b33c7d363',
    messagingSenderId: '170939507034',
    projectId: 'resik-sampah',
    authDomain: 'resik-sampah.firebaseapp.com',
    storageBucket: 'resik-sampah.firebasestorage.app',
    measurementId: 'G-TRCJ162KXX',
  );

}